# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'gsDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for gsDemo
  pod 'Firebase/Core'




  target 'gsDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'gsDemo-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for gsDemo-tvOS

  target 'gsDemo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
